---
name: 'Build and Push'

on:
  push:
    branches:
      - master

jobs:
  changes:
    name: Diff check
    runs-on: ubuntu-20.04
    outputs:
      engineering-base: ${{ steps.filter.outputs.engineering-base }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            engineering-base: 
              - '/spack/**'
              - '/rc/**'
              - 'lsf/**'
              - '*.pl'
              - 'Dockerfile'

  engineering-base:
    needs: changes
    if: ${{ needs.changes.outputs.engineering-base == 'true' }}      
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          tags: ghcr.io/washu-it-ris/engineering-base:latest
          push: true